icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[icons]
icons = "awesome"
[icons.overrides]
bat = " | | "
bat_full = " |X| "
bat_charging = " |^| "
bat_discharging = " |v| "

[[block]]
block = "cpu"

[[block]]
block = "memory"
display_type = "memory"
format_mem = " $icon $mem_free.eng(3,B,M)/$mem_total.eng(3,B,M) "

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = " %a %d/%m %R "
