icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[icons]
icons = "awesome"
[icons.overrides]
bat = " | | "
bat_full = " |X| "
bat_charging = " |^| "
bat_discharging = " |v| "

[[block]]
block = "cpu"

[[block]]
block = "memory"
display_type = "memory"
format_mem = " $icon $mem_total_used_percents.eng(2) "
format_swap = " $icon $swap_used_percents.eng(2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = " %a %d/%m %R "
