theme = "gruvbox"

[editor]
bufferline = "multiple"
mouse = true
auto-format = true
auto-pairs = false

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
