debug: false
order: [network, battery, audio, time]
separator: " / "

audio:
  control: Master
  mute: MUTE
  template:  {VOL}%
  icons: []

backlight:
  device: intel_backlight
  template: L {BL}%
  icons: []

battery:
  charging: ▲
  discharging: ▼
  enable_notifier: true
  no_battery: NO BATT
  notifier_critical: 10
  notifier_levels: [2, 5, 10, 15, 20]
  separator: " · "
  icons: []

cpu_load:
  template: "{CL1} {CL5} {CL15}"
  update_interval: 20

network:
  no_value: NA
  template: "  {ESSID}"

time:
  format: "%Y-%m-%d %H:%M"
  update_seconds: false
