[theme]
theme = "modern"

[icons]
icons = "awesome"

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid $frequency|Wifi} via $device "

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
locale = "en_IN"
[block.format]
full = "%a %d/%m %R "
short = " $icon %R "

[[block]]
block = "battery"
format = " $icon $percentage "
