icons_format = "{icon}"

[theme]
theme = "gruvbox-dark"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
icons = "awesome"

[[block]]
block = "cpu"

[[block]]
block = "battery"
format = " $icon $percentage "

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = " %a %d/%m %R "
